Update StatusCake provider to 2.1.0 (#629)
It was causing an issue when updating the SSL check:
Error: failed to update SSL check: Unexpected error. Try again later.